import { EnvironmentSecrets } from "@/types";

const {
    AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET,
    AUTH_SECRET,
    DATABASE_CONNECTION_STR,
    EMAIL_SERVICE_API_KEY,
    EMAIL_SERVICE_SECRET,
    NODE_ENV,
} = process.env as any as EnvironmentSecrets;

export default {
    AUTH_GOOGLE_ID: AUTH_GOOGLE_ID,
    AUTH_GOOGLE_SECRET: AUTH_GOOGLE_SECRET,
    AUTH_SECRET: AUTH_SECRET,
    DATABASE_CONNECTION_STR: DATABASE_CONNECTION_STR,
    EMAIL_SERVICE_API_KEY: EMAIL_SERVICE_API_KEY,
    EMAIL_SERVICE_SECRET: EMAIL_SERVICE_SECRET,
    NODE_ENV: NODE_ENV,
} as EnvironmentSecrets;
